Test: Skip Hunchentoot test on Windows.
It seems SBCL has difficulty closing threads on Windows. Windows support for
Lisps in general are so-so, especially for non commercial implementations.

Threads must be closed because dumping an image with multiple threads running is
undefined.

Source:
https://stackoverflow.com/questions/47888877/sbcl-building-a-standalone-executable

--- snip here ---

Error: 2-07 23:44:42 [ERROR]] Wake-for-shutdown connect failed: The condition Socket error in "connect": 10049 (The requested address is not valid in its context.) occurred with errno: 0.
While evaluating the form starting at line 92, column 0

  of #P"D:/a/project-isidore/project-isidore/bin/make.lisp":
Type HELP for debugger help, or (SB-EXT:EXIT) to exit from SBCL.

debugger invoked on a SB-SYS:INTERACTIVE-INTERRUPT @100008364D in thread
restarts (invokable by number or by possibly-abbreviated name):
  0: [CONTINUE                     ] Return from SB-WIN32::SIGINT.
  Interactive interrupt at #x100008364D.
  1: [RETRY                        ] Retry
;
                                     #<TEST-OP > on #<PACKAGE-INFERRED-SYSTEM "project-isidore-test">.
; compilation unit aborted
  2: [ACCEPT                       ] Continue, treating
;   caught 1 fatal ERROR condition
                                     #<TEST-OP > on #<PACKAGE-INFERRED-SYSTEM "project-isidore-test">
                                     as having been successful.
  3:                                 Retry ASDF operation.
  4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the
                                     configuration.
  5:                                 Retry ASDF operation.
  6:                                 Retry ASDF operation after resetting the
                                     configuration.
  7: [RETRY                        ] Retry EVAL of current toplevel form.
  8:                                 Ignore error and continue loading file "D:\\a\\project-isidore\\project-isidore\\bin\\make.lisp".
  9: [ABORT                        ] Abort loading file "D:\\a\\project-isidore\\project-isidore\\bin\\make.lisp".
 10:                                 Ignore runtime option --load "D:\\a\\project-isidore\\project-isidore\\bin\\make.lisp".
 11:                                 Skip rest of --eval and --load options.
 12:                                 Skip to toplevel READ/EVAL/PRINT loop.
 13: [EXIT                         ] Exit SBCL (calling #'EXIT, killing the process).

(SB-UNIX::WITH-DEFERRABLE-SIGNALS-UNBLOCKED T #<FUNCTION (FLET SB-UNIX::BODY :IN SB-THREAD::FUTEX-WAIT) {5FCAEB}>)
0]

--- snip here ---